export const GET_LIST_REQUEST = 'GET_LIST_REQUEST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAILURE = 'GET_LIST_FAILURE';
export const CHECK_LOGIN = 'CHECK_LOGIN';
export const LOGIN_CHECKED = 'LOGIN_CHECKED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const INCREMENT = 'INCREMENT';