// api calls
export const GET_LIST_REQUEST = 'GET_LIST_REQUEST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAILURE = 'GET_LIST_FAILURE';
export const POPULATE_SCORES = 'POPULATE_SCORES';
export const POST_SCORES_REQUEST = 'POST_SCORES_REQUEST';
export const POST_SCORES_SUCCESS = 'POST_SCORES_SUCCESS';

//login
export const CHECK_LOGIN = 'CHECK_LOGIN';
export const LOGIN_CHECKED = 'LOGIN_CHECKED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//nav
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

//score
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const COMMIT_SCORE = 'COMMIT_SCORE';

//form
export const INC_YEARS_EXP = 'INC_YEARS_EXP';
export const DEC_YEARS_EXP = 'DEC_YEARS_EXP';
export const INITIALISE = 'INITIALISE';
export const TOGGLE_SVT_ACCREDITED = 'TOGGLE_SVT_ACCREDITED';
export const TOGGLE_WORKING_TOWARDS_ACCREDITATION = 'TOGGLE_WORKING_TOWARDS_ACCREDITATION';

//test

export const TEST = 'TEST';


